default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: punx_booking_dev
  username: postgres
  password:

test:
  <<: *default
  database: punx_booking_test
  username: postgres
  password:

production:
  <<: *default
  database: punx_booking_production
