Country.new(name: 'Andorra', slug: 'AD')
Country.new(name: 'United Arab Emirates', slug: 'AE')
Country.new(name: 'Afghanistan', slug: 'AF')
Country.new(name: 'Antigua and Barbuda', slug: 'AG')
Country.new(name: 'Anguilla', slug: 'AI')
Country.new(name: 'Albania', slug: 'AL')
Country.new(name: 'Armenia', slug: 'AM')
Country.new(name: 'Netherlands Antilles', slug: 'AN')
Country.new(name: 'Angola', slug: 'AO')
Country.new(name: 'Antarctica', slug: 'AQ')
Country.new(name: 'Argentina', slug: 'AR')
Country.new(name: 'American Samoa', slug: 'AS')
Country.new(name: 'Austria', slug: 'AT')
Country.new(name: 'Australia', slug: 'AU')
Country.new(name: 'Aruba', slug: 'AW')
Country.new(name: 'Åland Islands', slug: 'AX')
Country.new(name: 'Azerbaijan', slug: 'AZ')
Country.new(name: 'Bosnia and Herzegovina', slug: 'BA')
Country.new(name: 'Barbados', slug: 'BB')
Country.new(name: 'Bangladesh', slug: 'BD')
Country.new(name: 'Belgium', slug: 'BE')
Country.new(name: 'Burkina Faso', slug: 'BF')
Country.new(name: 'Bulgaria', slug: 'BG')
Country.new(name: 'Bahrain', slug: 'BH')
Country.new(name: 'Burundi', slug: 'BI')
Country.new(name: 'Benin', slug: 'BJ')
Country.new(name: 'Saint Barthélemy', slug: 'BL')
Country.new(name: 'Bermuda', slug: 'BM')
Country.new(name: 'Brunei Darussalam', slug: 'BN')
Country.new(name: 'Bolivia', slug: 'BO')
Country.new(name: 'Bonaire, Sint Eustatius and Saba', slug: 'BQ')
Country.new(name: 'Brazil', slug: 'BR')
Country.new(name: 'Bahamas', slug: 'BS')
Country.new(name: 'Bhutan', slug: 'BT')
Country.new(name: 'Bouvet Island', slug: 'BV')
Country.new(name: 'Botswana', slug: 'BW')
Country.new(name: 'Belarus', slug: 'BY')
Country.new(name: 'Belize', slug: 'BZ')
Country.new(name: 'Canada', slug: 'CA')
Country.new(name: 'Cocos (Keeling) Islands', slug: 'CC')
Country.new(name: 'Congo, The Democratic Republic Of The', slug: 'CD')
Country.new(name: 'Central African Republic', slug: 'CF')
Country.new(name: 'Congo', slug: 'CG')
Country.new(name: 'Switzerland', slug: 'CH')
Country.new(name: "Côte D'Ivoire", slug: 'CI')
Country.new(name: 'Cook Islands', slug: 'CK')
Country.new(name: 'Chile', slug: 'CL')
Country.new(name: 'Cameroon', slug: 'CM')
Country.new(name: 'China', slug: 'CN')
Country.new(name: 'Colombia', slug: 'CO')
Country.new(name: 'Costa Rica', slug: 'CR')
Country.new(name: 'Cuba', slug: 'CU')
Country.new(name: 'Cape Verde', slug: 'CV')
Country.new(name: 'Curaçao', slug: 'CW')
Country.new(name: 'Christmas Island', slug: 'CX')
Country.new(name: 'Cyprus', slug: 'CY')
Country.new(name: 'Czech Republic', slug: 'CZ')
Country.new(name: 'Germany', slug: 'DE')
Country.new(name: 'Djibouti', slug: 'DJ')
Country.new(name: 'Denmark', slug: 'DK')
Country.new(name: 'Dominica', slug: 'DM')
Country.new(name: 'Dominican Republic', slug: 'DO')
Country.new(name: 'Algeria', slug: 'DZ')
Country.new(name: 'Ecuador', slug: 'EC')
Country.new(name: 'Estonia', slug: 'EE')
Country.new(name: 'Egypt', slug: 'EG')
Country.new(name: 'Western Sahara', slug: 'EH')
Country.new(name: 'Eritrea', slug: 'ER')
Country.new(name: 'Spain', slug: 'ES')
Country.new(name: 'Ethiopia', slug: 'ET')
Country.new(name: 'Finland', slug: 'FI')
Country.new(name: 'Fiji', slug: 'FJ')
Country.new(name: 'Falkland Islands (Malvinas)', slug: 'FK')
Country.new(name: 'Micronesia, Federated States Of', slug: 'FM')
Country.new(name: 'Faroe Islands', slug: 'FO')
Country.new(name: 'France', slug: 'FR')
Country.new(name: 'Gabon', slug: 'GA')
Country.new(name: 'United Kingdom', slug: 'GB')
Country.new(name: 'Grenada', slug: 'GD')
Country.new(name: 'Georgia', slug: 'GE')
Country.new(name: 'French Guiana', slug: 'GF')
Country.new(name: 'Guernsey', slug: 'GG')
Country.new(name: 'Ghana', slug: 'GH')
Country.new(name: 'Gibraltar', slug: 'GI')
Country.new(name: 'Greenland', slug: 'GL')
Country.new(name: 'Gambia', slug: 'GM')
Country.new(name: 'Guinea', slug: 'GN')
Country.new(name: 'Guadeloupe', slug: 'GP')
Country.new(name: 'Equatorial Guinea', slug: 'GQ')
Country.new(name: 'Greece', slug: 'GR')
Country.new(name: 'South Georgia and the South Sandwich Islands', slug: 'GS')
Country.new(name: 'Guatemala', slug: 'GT')
Country.new(name: 'Guam', slug: 'GU')
Country.new(name: 'Guinea-Bissau', slug: 'GW')
Country.new(name: 'Guyana', slug: 'GY')
Country.new(name: 'Hong Kong', slug: 'HK')
Country.new(name: 'Heard and McDonald Islands', slug: 'HM')
Country.new(name: 'Honduras', slug: 'HN')
Country.new(name: 'Croatia', slug: 'HR')
Country.new(name: 'Haiti', slug: 'HT')
Country.new(name: 'Hungary', slug: 'HU')
Country.new(name: 'Indonesia', slug: 'ID')
Country.new(name: 'Ireland', slug: 'IE')
Country.new(name: 'Israel', slug: 'IL')
Country.new(name: 'Isle of Man', slug: 'IM')
Country.new(name: 'India', slug: 'IN')
Country.new(name: 'British Indian Ocean Territory', slug: 'IO')
Country.new(name: 'Iraq', slug: 'IQ')
Country.new(name: 'Iran, Islamic Republic Of', slug: 'IR')
Country.new(name: 'Iceland', slug: 'IS')
Country.new(name: 'Italy', slug: 'IT')
Country.new(name: 'Jersey', slug: 'JE')
Country.new(name: 'Jamaica', slug: 'JM')
Country.new(name: 'Jordan', slug: 'JO')
Country.new(name: 'Japan', slug: 'JP')
Country.new(name: 'Kenya', slug: 'KE')
Country.new(name: 'Kyrgyzstan', slug: 'KG')
Country.new(name: 'Cambodia', slug: 'KH')
Country.new(name: 'Kiribati', slug: 'KI')
Country.new(name: 'Comoros', slug: 'KM')
Country.new(name: 'Saint Kitts And Nevis', slug: 'KN')
Country.new(name: "Korea, Democratic People's Republic Of", slug: 'KP')
Country.new(name: 'Korea, Republic of', slug: 'KR')
Country.new(name: 'Kuwait', slug: 'KW')
Country.new(name: 'Cayman Islands', slug: 'KY')
Country.new(name: 'Kazakhstan', slug: 'KZ')
Country.new(name: "Lao People's Democratic Republic", slug: 'LA')
Country.new(name: 'Lebanon', slug: 'LB')
Country.new(name: 'Saint Lucia', slug: 'LC')
Country.new(name: 'Liechtenstein', slug: 'LI')
Country.new(name: 'Sri Lanka', slug: 'LK')
Country.new(name: 'Liberia', slug: 'LR')
Country.new(name: 'Lesotho', slug: 'LS')
Country.new(name: 'Lithuania', slug: 'LT')
Country.new(name: 'Luxembourg', slug: 'LU')
Country.new(name: 'Latvia', slug: 'LV')
Country.new(name: 'Libya', slug: 'LY')
Country.new(name: 'Morocco', slug: 'MA')
Country.new(name: 'Monaco', slug: 'MC')
Country.new(name: 'Moldova, Republic of', slug: 'MD')
Country.new(name: 'Montenegro', slug: 'ME')
Country.new(name: 'Saint Martin', slug: 'MF')
Country.new(name: 'Madagascar', slug: 'MG')
Country.new(name: 'Marshall Islands', slug: 'MH')
Country.new(name: 'Macedonia', slug: 'MK')
Country.new(name: 'Mali', slug: 'ML')
Country.new(name: 'Myanmar', slug: 'MM')
Country.new(name: 'Mongolia', slug: 'MN')
Country.new(name: 'Macao', slug: 'MO')
Country.new(name: 'Northern Mariana Islands', slug: 'MP')
Country.new(name: 'Martinique', slug: 'MQ')
Country.new(name: 'Mauritania', slug: 'MR')
Country.new(name: 'Montserrat', slug: 'MS')
Country.new(name: 'Malta', slug: 'MT')
Country.new(name: 'Mauritius', slug: 'MU')
Country.new(name: 'Maldives', slug: 'MV')
Country.new(name: 'Malawi', slug: 'MW')
Country.new(name: 'Mexico', slug: 'MX')
Country.new(name: 'Malaysia', slug: 'MY')
Country.new(name: 'Mozambique', slug: 'MZ')
Country.new(name: 'Namibia', slug: 'NA')
Country.new(name: 'New Caledonia', slug: 'NC')
Country.new(name: 'Niger', slug: 'NE')
Country.new(name: 'Norfolk Island', slug: 'NF')
Country.new(name: 'Nigeria', slug: 'NG')
Country.new(name: 'Nicaragua', slug: 'NI')
Country.new(name: 'Netherlands', slug: 'NL')
Country.new(name: 'Norway', slug: 'NO')
Country.new(name: 'Nepal', slug: 'NP')
Country.new(name: 'Nauru', slug: 'NR')
Country.new(name: 'Niue', slug: 'NU')
Country.new(name: 'New Zealand', slug: 'NZ')
Country.new(name: 'Oman', slug: 'OM')
Country.new(name: 'Panama', slug: 'PA')
Country.new(name: 'Peru', slug: 'PE')
Country.new(name: 'French Polynesia', slug: 'PF')
Country.new(name: 'Papua New Guinea', slug: 'PG')
Country.new(name: 'Philippines', slug: 'PH')
Country.new(name: 'Pakistan', slug: 'PK')
Country.new(name: 'Poland', slug: 'PL')
Country.new(name: 'Saint Pierre And Miquelon', slug: 'PM')
Country.new(name: 'Pitcairn', slug: 'PN')
Country.new(name: 'Puerto Rico', slug: 'PR')
Country.new(name: 'Palestine', slug: 'PS')
Country.new(name: 'Portugal', slug: 'PT')
Country.new(name: 'Palau', slug: 'PW')
Country.new(name: 'Paraguay', slug: 'PY')
Country.new(name: 'Qatar', slug: 'QA')
Country.new(name: 'Réunion', slug: 'RE')
Country.new(name: 'Romania', slug: 'RO')
Country.new(name: 'Serbia', slug: 'RS')
Country.new(name: 'Russia', slug: 'RU')
Country.new(name: 'Rwanda', slug: 'RW')
Country.new(name: 'Saudi Arabia', slug: 'SA')
Country.new(name: 'Solomon Islands', slug: 'SB')
Country.new(name: 'Seychelles', slug: 'SC')
Country.new(name: 'Sudan', slug: 'SD')
Country.new(name: 'Sweden', slug: 'SE')
Country.new(name: 'Singapore', slug: 'SG')
Country.new(name: 'Saint Helena', slug: 'SH')
Country.new(name: 'Slovenia', slug: 'SI')
Country.new(name: 'Svalbard And Jan Mayen', slug: 'SJ')
Country.new(name: 'Slovakia', slug: 'SK')
Country.new(name: 'Sierra Leone', slug: 'SL')
Country.new(name: 'San Marino', slug: 'SM')
Country.new(name: 'Senegal', slug: 'SN')
Country.new(name: 'Somalia', slug: 'SO')
Country.new(name: 'Suriname', slug: 'SR')
Country.new(name: 'South Sudan', slug: 'SS')
Country.new(name: 'Sao Tome and Principe', slug: 'ST')
Country.new(name: 'El Salvador', slug: 'SV')
Country.new(name: 'Sint Maarten', slug: 'SX')
Country.new(name: 'Syrian Arab Republic', slug: 'SY')
Country.new(name: 'Swaziland', slug: 'SZ')
Country.new(name: 'Turks and Caicos Islands', slug: 'TC')
Country.new(name: 'Chad', slug: 'TD')
Country.new(name: 'French Southern Territories', slug: 'TF')
Country.new(name: 'Togo', slug: 'TG')
Country.new(name: 'Thailand', slug: 'TH')
Country.new(name: 'Tajikistan', slug: 'TJ')
Country.new(name: 'Tokelau', slug: 'TK')
Country.new(name: 'Timor-Leste', slug: 'TL')
Country.new(name: 'Turkmenistan', slug: 'TM')
Country.new(name: 'Tunisia', slug: 'TN')
Country.new(name: 'Tonga', slug: 'TO')
Country.new(name: 'Turkey', slug: 'TR')
Country.new(name: 'Trinidad and Tobago', slug: 'TT')
Country.new(name: 'Tuvalu', slug: 'TV')
Country.new(name: 'Taiwan, Republic Of China', slug: 'TW')
Country.new(name: 'Tanzania, United Republic of', slug: 'TZ')
Country.new(name: 'Ukraine', slug: 'UA')
Country.new(name: 'Uganda', slug: 'UG')
Country.new(name: 'United States Minor Outlying Islands', slug: 'UM')
Country.new(name: 'United States', slug: 'US')
Country.new(name: 'Uruguay', slug: 'UY')
Country.new(name: 'Uzbekistan', slug: 'UZ')
Country.new(name: 'Saint Vincent And The Grenedines', slug: 'VC')
Country.new(name: 'Venezuela, Bolivarian Republic of', slug: 'VE')
Country.new(name: 'Virgin Islands, British', slug: 'VG')
Country.new(name: 'Virgin Islands, U.S.', slug: 'VI')
Country.new(name: 'Vietnam', slug: 'VN')
Country.new(name: 'Vanuatu', slug: 'VU')
Country.new(name: 'Wallis and Futuna', slug: 'WF')
Country.new(name: 'Samoa', slug: 'WS')
Country.new(name: 'Yemen', slug: 'YE')
Country.new(name: 'Mayotte', slug: 'YT')
Country.new(name: 'South Africa', slug: 'ZA')
Country.new(name: 'Zambia', slug: 'ZM')
Country.new(name: 'Zimbabwe', slug: 'ZW')